RunScan:
  scan:
    start_nm: 739.50
    end_nm: 739.55
    auto_scan_speed_from_kinetic: true
    ws7_sample_period_s: 0.02
    power_sample_period_s: 0.05
    max_run_time_s: 600

  instruments:
    detector:
      mode: "andor_kinetic"
      andor_kinetic:
        exposure_s: 0.10
        cycle_s: 0.15
        n_frames: 200
        cool_down: false           # since you keep cooler on
        temperature_C: -65


output:
  path: "data/scan_001.h5"


